#!/bin/bash

if [ ! -d data_files ]; then
  mkdir -p data_files;
fi


gcc -L/usr/local/lib/gsl "Monte_Carlo.c" -lgsl -lgslcblas -lm -o exc

LD_LIBRARY_PATH=/usr/local/lib/gsl GSL_RNG_TYPE="taus" GSL_RNG_SEED=$1 ./exc $2



