#!/bin/bash

if [ ! -d data_files ]; then
  mkdir -p data_files;
fi

if [ ! -d ../../Results/Monte_Carlo ]; then
  mkdir -p ../../Results/Monte_Carlo ;
fi


gcc -L/usr/local/lib/gsl "Teste_Carlo.c" -lgsl -lgslcblas -lm -o exc

LD_LIBRARY_PATH=/usr/local/lib/gsl GSL_RNG_TYPE="taus" GSL_RNG_SEED=$1 ./exc $2


python plots.py $1 $2
